### PR TITLE
Support for JSON Feed 1.1

### LINKED ISSUE #6: Add support for JSON Feed
Add a module to support JSON Feed. 

https://jsonfeed.org/version/1

### PR DESCRIPTION
**Pull request by Mark1626**
Closes #6 

As per the request implemented support for JSON Feed 1.1, which seems to be the latest verison

Summary:
- Module `jsonfeed` has been added, as per the [JSON Feed 1.1 Specification](https://jsonfeed.org/version/1.1) 
- Property `micronaut.rss.feed.jsonfeed` must be set `true`, default is `false`
- `JsonFeedRenderer` utilises `fasterxml.jackson` for rendering the JSON
- `JsonFeedController` will replace the `FeedController`
- Tests have been added

Points which came up when I implemented it:
- The MIME type of JSON feed is `application/json+feed`, which was not present in the default MimeType
- Reused `RssLanguage` for the Json Feed `language` fields, as per the specification it should be `rfc5646` compliant; need to check this
- As per the specification atleast one of `contentHtml` or `contentText` needs to be present, I didn't add a validation for it because it didn't seem straight forward and I'm not sure if that concern should belong to this module

Let me know if you need any changes to be made

### CODE REVIEW

**Comment by Mark1626** [comment]
Fixing the checkstyle issues

**Comment by sdelamo** [comment]
thanks @Mark1626 I will try to review this next week.

**Comment by sdelamo** [comment]
@Mark1626 Thanks for your contributions. 

I have created two modules `jsonfeed-core` for the core classes and `jsonfeed` if you want a `/feeds/json` endpoint. 

I have used your code and split it in two PRs: 

- https://github.com/micronaut-projects/micronaut-rss/pull/62

- https://github.com/micronaut-projects/micronaut-rss/pull/61

> Property micronaut.rss.feed.jsonfeed must be set true, default is false

I've created a controller which exposes `/feeds/json` if you provide a bean of type [JsonFeedProvider](https://github.com/micronaut-projects/micronaut-rss/blob/master/jsonfeed/src/main/java/io/micronaut/rss/jsonfeed/http/JsonFeedProvider.java) such as [ExampleJsonFeedProvider.java](https://github.com/micronaut-projects/micronaut-rss/blob/master/jsonfeed/src/test/java/io/micronaut/rss/jsonfeed/http/ExampleJsonFeedProvider.java)

> JsonFeedRenderer utilises fasterxml.jackson for rendering the JSON
> JsonFeedController will replace the FeedController

I have used Jackson `@JsonProperty` annotations in the POJOs and use the default json rendering instead of the use `JsonFeedRenderer`. I hope you don't mind. 

> The MIME type of JSON feed is application/json+feed, which was not present in the default MimeType

Users will need to register an additional JSON Codec. I have included this in the docs and in the tests. 

example: 

https://github.com/micronaut-projects/micronaut-rss/blob/master/jsonfeed/src/test/resources/application.yml

>  Reused RssLanguage for the Json Feed language fields, as per the specification it should be rfc5646 compliant; need to check this

I have changed the `JsonFeed` POJO to use a String for `language`. I have left however a method in the builder to accept `RssLanguage as method parameter. 

> As per the specification at least one of contentHtml or contentText needs to be present, I didn't add a validation for it because it didn't seem straight forward and I'm not sure if that concern should belong to this module

I will create a separate task for this. I don't think it is huge priority. We will need a custom constraint to support this. 


I have deleted the deprecated `author` for JSON Feed 1.0 I hope you don't mind. I think it is easier to just maintain 1.1. forward. 

Other changes:

## Use Introspected for POJOs

Instead of final classes such as: 


```java
public final class JsonFeed {
```

We use `@Introspected`  for POJOs. 

```java
@Introspected
public class JsonFeed {
```

See [Bean Introspection](https://docs.micronaut.io/latest/guide/index.html#introspection)


## Spot Bugs @Nullable @NonNull annotations

- We use  Spot Bugs Instead of JSR-305 Nullable/NonNull Annotations

We use: 

```java
import edu.umd.cs.findbugs.annotations.Nullable;
```

instead of: 

```java
import javax.annotation.Nullable;
```


Please, let know if you have concerns with the changes I did.

Thanks a lot for your contribution. It is cool to support JSON Feeds.

**Comment by Mark1626** [comment]
> I have used Jackson `@JsonProperty` annotations in the POJOs and use the default json rendering instead of the use `JsonFeedRenderer`.

I've mostly used the default renderer in my other projects, I went for the streaming API in this case for performance purposes, also that I noticed the XML feed also was using streaming APIs as well.

> I have deleted the deprecated `author` for JSON Feed 1.0 I hope you don't mind. I think it is easier to just maintain 1.1. forward.

Makes sense, the JSON feed reader has the responsibility to support previous versions rather than the feed provider

Thanks for the opportunity @sdelamo

**Comment by sdelamo** [comment]
>> I have used Jackson @JsonProperty annotations in the POJOs and use the default json rendering instead of the use JsonFeedRenderer.

> I've mostly used the default renderer in my other projects, I went for the streaming API in this case for performance purposes, also that I noticed the XML feed also was using streaming APIs as well.

@Mark1626 Will it be useful for your use cases to have a bean of type: 

```
@FunctionalInterface
 public interface JsonFeedRenderer {
     /**
      * Writes an RSS channel to a {@link java.io.Writer}.
      * @param rssChannel The RSS channel to render
      * @param writer A Writer to write the RSS feed into
      */
     void render(Writer writer, JsonFeed rssChannel);
 }
```

even if the `JsonFeedController` does not use it?

**Comment by Mark1626** [comment]
The current implementation is fine for my usecase. The `JsonFeedRenderer` interface is not needed

**Pull request closed without merging**
